// react_uxuan/frontend/src/components/Category.jsx
import React, { Component } from 'react'
import "../css/Category.css"
import { NavLink, Route, Switch, Redirect } from "react-router-dom"
import CategoryChild from "./CategoryChild"
export default class Category extends Component {
    constructor(props) {
        super(props)
        this.state = {
            categoryList: []
        }
    }
    componentDidMount() {
        this.$axios("/api/getcate").then((res) => {
            if (res.data.code === 200) {
                this.setState({
                    categoryList: res.data.list
                })
            }
        })
    }
    render() {
        return (
            <main id="category">
                <header>
                    <h2>商品分类</h2>
                    <div className="search-wrapper-relative">
                        <input type="text" placeholder="按内容搜索" />
                        <div className="searchLogo"></div>
                        <button>搜索</button>
                    </div>
                </header>
                <article>
                    <div className="left-wrapper">
                        <ul>
                            {
                                this.state.categoryList.map((item,_index)=>{
                                    return(
                                        <li key={item.id}>
                                            <NavLink to={{pathname:"/category/"+item.id}}>{item.catename}</NavLink>
                                        </li>
                                    )
                                })
                            }
                        </ul>
                    </div>
                    <Switch>
                        <Route path="/category/:id" component={CategoryChild}></Route>
                        <Redirect from="/category" to="/category/1"></Redirect>
                    </Switch>
                </article>
            </main>
        )
    }
}

// vue_ushop/front/src/components/category.vue
<template>
    <article id="category">
        <header>
            <div class="search-wrapper-relative">
                <input type="text" placeholder="按内容搜索" />
                <input type="submit" value="" />
            </div>
        </header>
        <main>
            <div class="left-wrapper">
                <ul>
                    <router-link
                        v-for="item in category"
                        :key="item.id"
                        :to="'/category/'+item.params"
                        tag="li"
                        exact-active-class="active"
                        >{{ item.catename }}</router-link
                    >
                </ul>
            </div>
            <router-view></router-view>
        </main>
    </article>
</template>

<script>
export default {
    data() {
        return {
            category: [],
        };
    },
    created() {
        this.$axios.get("/api/catelist").then((res) => {
            this.category = res.data.list;
        });
    },
};
</script>

<style scoped lang="scss">
@import "../assets/scss/category.scss";
</style>
