// react_uxuan/frontend/src/components/Detail.jsx
import React, { Component } from 'react'
import { Carousel, WingBlank } from 'antd-mobile';
import "../css/Detail.css"

export default class Detail extends Component {
    state = {
        list: {
            goodsname: "",
            price: "",
            market_price: "",
        },
        data: ['AiyWuByWklrrUDlFignR', 'TekJlZRVCjLFexlOCuWn', 'IJOtIlfsYdTyaDTRVrLI'],
        imgHeight: 176,
    }
    componentDidMount() {
        let { id } = this.props.match.params
        this.$axios.get("/api/getgoodsinfo?id=" + id).then(res => {
            if (res.data.code === 200) {
                this.setState({
                    list: res.data.list[0]
                })
            }
        })
    }
    back=()=>{
        this.props.history.go(-1)
    }
    addShopCart=()=>{
        let uid = sessionStorage.getItem("uid")
        let {id} = this.props.match.params
        uid !== null
        ?
        this.$axios.post("/api/cartadd",{uid:uid,type:"1",goodsid:id,num:1})
        :
        this.props.history.push({pathname:"/login",search:"?path=/detail/"+id})
    }
    redirectToShopCart=()=>{
        this.props.history.push("/shopcart")
    }
    render() {
        return (
            <main id="detail">
                <header>
                    <div className="headNameBox">
                        <button onClick={this.back}>Back</button>
                        <h2>
                            {this.state.list.goodsname}
                        </h2>
                    </div>
                    <div className="buttonBox">
                        <button>商品</button>
                        <button>评价</button>
                        <button>详情</button>
                        <button>推荐</button>
                    </div>
                </header>
                <WingBlank>
                    <Carousel
                        autoplay={true}
                        infinite
                        autoplayInterval={1000}
                    >
                        {this.state.data.map((val,index) => (
                            <img
                                key={index}
                                src={`https://zos.alipayobjects.com/rmsportal/${val}.png`}
                                alt=""
                                style={{ width: '100%', verticalAlign: 'top' }}
                                onLoad={() => {
                                    // fire window resize event to change height
                                    window.dispatchEvent(new Event('resize'));
                                    this.setState({ imgHeight: 'auto' });
                                }}
                            />
                        ))}
                    </Carousel>
                </WingBlank>
                <article>
                    <div className="priceBox">
                        <span>&yen;{this.state.list.price}</span>
                        <span>&yen;{this.state.list.market_price}</span>
                    </div>
                    <div className="description">
                        <span>描述占位</span>
                    </div>
                </article>
                <div className="footer">
                    <div>客服</div>
                    <div>店铺</div>
                    <div onClick={this.redirectToShopCart}>购物车</div>
                    <div className="addShopCart" onClick={this.addShopCart}>加入购物车</div>
                    <div className="buyNow">立即购买</div>
                </div>
            </main >
        )
    }
}

// vue_ushop/front/src/views/detail.vue
<template>
    <article id="detail">
        <header>
            <div class="title">
                <!-- 返回按钮,使用go方法能够返回历史的上一条记录 -->
                <button @click="$router.go(-1)">&lt;</button>
                <h2>{{ obj.goodsname }}</h2>
            </div>
            <nav>
                <button>商品</button>
                <button>评价</button>
                <button>详情</button>
                <button>推荐</button>
            </nav>
        </header>
        <main>
            <img :src="obj.img" alt="" />
            <div class="infoBox">
                <p class="price">
                    <span class="nowPrice">&yen;{{ obj.price }}</span>
                    <span class="oldPrice">&yen;9999</span>
                </p>
                <p class="name">{{ obj.goodsname }}</p>
                <p class="description">
                    这里是描述占位 这里是描述占位 这里是描述占位
                </p>
            </div>
            <footer>
                <div class="operate1">
                    <div>客服</div>
                    <div>店铺</div>
                    <div>购物车</div>
                </div>
                <div class="operate2">
                    <div class="addCart">加入购物车</div>
                    <div class="buyNow">立即购买</div>
                </div>
            </footer>
        </main>
    </article>
</template>

<script>
import axios from "axios";
export default {
    created() {
        // 发送axios请求,获取商品的详细信息
        axios.get("/api/goodsinfo?id=" + this.$route.params.id).then((res) => {
            console.log(res.data);
            this.obj = res.data.list;
        });
    },
    data() {
        return {
            obj: {},
        };
    },
};
</script>

<style scoped lang="scss">
@import "../assets/scss/detail.scss";
</style>
