// vue_ushop/front/src/components/shopCart.vue
<template>
    <article id="shopCart">
        <div v-if="noData">
            <div class="viewWrapper">
                <section v-for="(item, index) in numberId" :key="index">
                    <div class="selectBox">
                        <label>
                            <input
                                type="checkbox"
                                :checked="item.flag"
                                @change="changeFlag(item.first_cateid)"
                            />
                        </label>
                    </div>
                    <img v-bind:src="item.img" alt="" />
                    <div class="itemInfo">
                        <p class="name">{{ item.goodsname }}</p>
                        <div class="countBox">
                            <span class="price">&yen;{{ item.price }}</span>
                            <div class="numberBox">
                                <button
                                    v-on:click="
                                        changeCount({
                                            first_cateid: item.first_cateid,
                                            type: 'dec',
                                        })
                                    "
                                >
                                    -
                                </button>
                                <span class="itemCount">{{ item.num }}</span>
                                <button
                                    v-on:click="
                                        changeCount({
                                            first_cateid: item.first_cateid,
                                            type: 'inc',
                                        })
                                    "
                                >
                                    +
                                </button>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <footer>
                <div class="allSelectBox">
                    <input type="checkbox" v-model="allSelectBox" id="all"/>
                </div>
                <label for="all">
                    <p class="allSelectDecoration">全选</p>
                </label>
                <p class="priceCountBox">
                    <span>数量总和:{{ allCount }}</span>
                    <span
                        >价格总和:<b class="price"
                            >&yen;{{ allPriceCount.toFixed(2) }}</b
                        ></span
                    >
                </p>
                <button>结算</button>
            </footer>
        </div>
        <div v-else>
            <h2>购物车为空</h2>
        </div>
    </article>
</template>

<script>
import { mapMutations, mapState, mapGetters } from "vuex";
export default {
    data() {
        return {
            noData:false
        }
    },
    computed: {
        // 获取vuex中的购物车数据
        ...mapState({ numberId: "shopCart" }),
        // 全选框状态
        allSelectBox: {
            set(effect) {
                this.changeAll(effect);
            },
            get() {
                return this.numberId.every((item) => item.flag);
            },
        },
        // 获取总价格,总数量
        ...mapGetters(["allCount", "allPriceCount"]),
    },
    created() {
        if (this.numberId.length == 0) {
            this.noData = false
        }else{
            this.noData = true
        }
    },
    methods: {
        /**
         * changeCount 改变数量
         * changeFlag 改变选中状态
         * changeAll 全选框状态
         */
        ...mapMutations(["changeCount", "changeFlag", "changeAll"]),
    },
};
</script>

<style lang="scss" scoped>
@import "../assets/scss/shopCart.scss";
</style>

// react_uxuan/frontend/src/components/ShopCart.jsx
import React, { Component } from 'react'
import { connect } from "react-redux"
import "../css/ShopCart.css"
import ActionCreator from '../action/ActionCreator'
import { createSelector } from "reselect"
class ShopCart extends Component {
    componentDidMount() {
        this.props.getData()
    }

    change = (x) => {
        this.props.changeSelect(x)
    }

    selectAllButton = () => {
        this.props.selectAllButton()
    }

    numberChange(type){
        this.props.changeNumber(type)
    }

    render() {
        return (
            <main id="shopcart">
                <header>
                    <h2>购物车</h2>
                    <div className="buttonBox">
                        <button>全部</button>
                        <button>降价</button>
                        <button>常卖</button>
                        <button>分类</button>
                    </div>
                </header>
                <article>
                    <ul>
                        {/* <li>
                            <input type="checkbox" /> 普通商品
                        </li> */}
                        {
                            this.props.ShopCart.list.map(item => {
                                switch (item.type) {
                                    case 1:
                                        return (
                                            <li key={item.id}>
                                                <div className="selectBox">
                                                    <input type="checkbox" checked={item.checked} onChange={this.change.bind(this, item)} />
                                                </div>
                                                <div className="imgBox">
                                                    <img src={item.img} alt="" />
                                                </div>
                                                <div className="info">
                                                    <div className="goodsName">{item.goodsname}</div>
                                                    <p>&yen;{item.price}</p>
                                                    <div className="numberBox">
                                                        <button onClick={this.numberChange.bind(this,{type:-1,item})}>-</button>
                                                        <span>{item.num}</span>
                                                        <button onClick={this.numberChange.bind(this,{type:1,item})}>+</button>
                                                    </div>
                                                </div>
                                            </li>
                                        )
                                    default:
                                        break;
                                }
                            })
                        }
                    </ul>
                </article>
                <footer>
                    <div className="allSelectBox">
                        <input type="checkbox" id="all" checked={this.props.selectAllEffect} onChange={this.selectAllButton} />
                    </div>
                    <label htmlFor="all">
                        <p className="allSelectDecoration" >全选</p>
                    </label>
                    <p className="priceCountBox">
                        <span>数量总和:{this.props.countSum}</span>
                        <span>价格总和:
                            <b className="price">&yen;{this.props.priceSum.toFixed(2)}</b>
                        </span>
                    </p>
                    <button>结算</button>
                </footer>
            </main>
        )
    }
}
// TAG 全选钮状态
let selectAllEffect = createSelector(
    state => {
        return state.ShopCart.list
    },
    list => {
        return list.every(x => x.checked)
    }
)
// TAG 总数量
let countSum = createSelector(
    state => state.ShopCart.list,
    list => {
        return list.reduce((a, b) => a + (b.checked ? b.num : 0), 0)
    }
)
// TAG 总价
let priceSum = createSelector(
    state => state.ShopCart.list,
    list => {
        return list.reduce((a, b) => a + (b.checked ? b.num * b.price : 0), 0)
    }
)
let mapState = (state) => {
    return {
        ...state,
        selectAllEffect: selectAllEffect(state),
        countSum: countSum(state),
        priceSum: priceSum(state)
    }
}
export default connect(mapState, ActionCreator)(ShopCart)
